sterror: add. documentation for Error
Remove 'Undefined' Scope

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

remove String() methods for string types

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

make Error.Info type string

Since everything else has its own type the E() function can
treat any extra string arg as this info.

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

documentation

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

handle call to E with no args

Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>